### ISSUE TITLE
Choice of MFCC

### ISSUE THREAD

**Issue by free-soellingeraj** [rezachu/emotion_recognition_cnn#7]
In the first paragraph of  the article linked with regard to your base audio transformation (MFCC) (http://practicalcryptography.com/miscellaneous/machine-learning/guide-mel-frequency-cepstral-coefficients-mfccs/), it goes "The first step in any automatic speech recognition system is to extract features i.e. identify the components of the audio signal that are good for identifying the linguistic content and discarding all the other stuff which carries information like background noise, **emotion** etc."

It wasn't addressed in your article, but I wonder if you put any thought into whether MFCC was causing problems because emotions are smoothed out of the dataset?  That is one of the stated goals of MFCC, per the above passage.

I would value your perspective.  Thanks for the blog!

**Comment by rezachu** [comment]
Hi Aaron,

Thanks for the message, I didn't put effort on the data preprocessing yet.
What I concerned the most is the fundamental dimension like:
1. how to define the emotions
2. how to label the emotions. , etc.
On the other hand, the reason why the CNN model is not a good approach is
it can only capture audio features. It cannot handle the contextual feature.
I read a paper lately which is the state of the art in SER issued last
August.
DialogueGCN: A Graph Convolutional Neural Network for Emotion Recognition
in Conversation

Here is a good blog explained the core concept of the paper.
https://towardsdatascience.com/emotion-recognition-using-graph-convolutional-networks-9f22f04b244e

The main concept of Dialogue GCN is it can capture the contextual
information and it can aggregating the information of neighbors which
compensated the weakness of LSTM.

**Comment by free-soellingeraj** [comment]
OK, I think I should do some exploratory data analysis.  I am in the
planning stage still.  I think the concern is that the Fourier transform /
aggregation process that exists in the MFCC step might be removing
information that could be used to better features that correspond to
emotions.

I also share the concerns that you put forward about the labeling
challenges of emotions.  Part of my background is in preference
elicitation.  I also think that a useful decision model may be possible to
be built on top of the existing model, even though the accuracy is not
super high.  Humans hardly assess each others' emotions correctly, or their
own.  That is a big challenge for this type of modeling, but also a major
value if it can be overcome.

Do you want me to fork the repo?  Maybe we could collaborate on it.

--aaron

**Comment by free-soellingeraj** [comment]
We talked.  I think this is closed
